/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.21
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */


#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#if defined(_WIN32) || defined(__CYGWIN32__)
#  define DllExport   __declspec( dllexport )
#  define SWIGSTDCALL __stdcall
#else
#  define DllExport  
#  define SWIGSTDCALL
#endif 


/* Support for throwing C# exceptions from C/C++ */
typedef enum {
  SWIG_CSharpException,
  SWIG_CSharpOutOfMemoryException,
  SWIG_CSharpIndexOutOfRangeException,
  SWIG_CSharpDivideByZeroException,
  SWIG_CSharpArgumentOutOfRangeException,
  SWIG_CSharpNullReferenceException
} SWIG_CSharpExceptionCodes;

typedef void (SWIGSTDCALL* SWIG_CSharpExceptionCallback_t)(const char *);

typedef struct {
  SWIG_CSharpExceptionCodes code;
  SWIG_CSharpExceptionCallback_t callback;
} SWIG_CSharpExceptions_t;

static SWIG_CSharpExceptions_t SWIG_csharp_exceptions[] = {
  { SWIG_CSharpException, NULL },
  { SWIG_CSharpOutOfMemoryException, NULL },
  { SWIG_CSharpIndexOutOfRangeException, NULL },
  { SWIG_CSharpDivideByZeroException, NULL },
  { SWIG_CSharpArgumentOutOfRangeException, NULL },
  { SWIG_CSharpNullReferenceException, NULL } };

static void SWIG_CSharpThrowException(SWIG_CSharpExceptionCodes code, const char *msg) {
  SWIG_CSharpExceptionCallback_t callback = SWIG_csharp_exceptions[SWIG_CSharpException].callback;
  if (code >=0 && (size_t)code < sizeof(SWIG_csharp_exceptions)/sizeof(SWIG_CSharpExceptionCodes)) {
    callback = SWIG_csharp_exceptions[code].callback;
  }
  callback(msg);
}


#ifdef __cplusplus
extern "C" 
#endif
DllExport void SWIGSTDCALL SWIGRegisterExceptionCallbacks_rlib(SWIG_CSharpExceptionCallback_t systemException,
                                                          SWIG_CSharpExceptionCallback_t outOfMemory, 
                                                          SWIG_CSharpExceptionCallback_t indexOutOfRange, 
                                                          SWIG_CSharpExceptionCallback_t divideByZero, 
                                                          SWIG_CSharpExceptionCallback_t argumentOutOfRange,
                                                          SWIG_CSharpExceptionCallback_t nullReference) {
  SWIG_csharp_exceptions[SWIG_CSharpException].callback = systemException;
  SWIG_csharp_exceptions[SWIG_CSharpOutOfMemoryException].callback = outOfMemory;
  SWIG_csharp_exceptions[SWIG_CSharpIndexOutOfRangeException].callback = indexOutOfRange;
  SWIG_csharp_exceptions[SWIG_CSharpDivideByZeroException].callback = divideByZero;
  SWIG_csharp_exceptions[SWIG_CSharpArgumentOutOfRangeException].callback = argumentOutOfRange;
  SWIG_csharp_exceptions[SWIG_CSharpNullReferenceException].callback = nullReference;
}


/* Callback for returning strings to C# without leaking memory */
typedef char * (SWIGSTDCALL* SWIG_CSharpStringHelperCallback)(const char *);
static SWIG_CSharpStringHelperCallback SWIG_csharp_string_callback = NULL;


#ifdef __cplusplus
extern "C" 
#endif
DllExport void SWIGSTDCALL SWIGRegisterStringCallback_rlib(SWIG_CSharpStringHelperCallback callback) {
  SWIG_csharp_string_callback = callback;
}

/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_CSharpThrowException(SWIG_CSharpArgumentOutOfRangeException, msg); return nullreturn; } else


#include <rlib.h>
 

#ifdef __cplusplus
extern "C" {
#endif

DllExport void * SWIGSTDCALL CSharp_rlib_init() {
    void * jresult = 0 ;
    rlib *result;
    
    result = (rlib *)rlib_init();
    
    jresult = (void *)result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_rlib_add_datasource_mysql(void * jarg1, char * jarg2, char * jarg3, char * jarg4, char * jarg5, char * jarg6) {
    int jresult = 0 ;
    rlib *arg1 = (rlib *) 0 ;
    char *arg2 ;
    char *arg3 ;
    char *arg4 ;
    char *arg5 ;
    char *arg6 ;
    int result;
    
    arg1 = (rlib *)jarg1; 
    arg2 = jarg2; 
    arg3 = jarg3; 
    arg4 = jarg4; 
    arg5 = jarg5; 
    arg6 = jarg6; 
    result = (int)rlib_add_datasource_mysql(arg1,arg2,arg3,arg4,arg5,arg6);
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_rlib_add_datasource_postgres(void * jarg1, char * jarg2, char * jarg3) {
    int jresult = 0 ;
    rlib *arg1 = (rlib *) 0 ;
    char *arg2 ;
    char *arg3 ;
    int result;
    
    arg1 = (rlib *)jarg1; 
    arg2 = jarg2; 
    arg3 = jarg3; 
    result = (int)rlib_add_datasource_postgres(arg1,arg2,arg3);
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_rlib_add_datasource_odbc(void * jarg1, char * jarg2, char * jarg3, char * jarg4, char * jarg5) {
    int jresult = 0 ;
    rlib *arg1 = (rlib *) 0 ;
    char *arg2 ;
    char *arg3 ;
    char *arg4 ;
    char *arg5 ;
    int result;
    
    arg1 = (rlib *)jarg1; 
    arg2 = jarg2; 
    arg3 = jarg3; 
    arg4 = jarg4; 
    arg5 = jarg5; 
    result = (int)rlib_add_datasource_odbc(arg1,arg2,arg3,arg4,arg5);
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_rlib_add_datasource_xml(void * jarg1, char * jarg2) {
    int jresult = 0 ;
    rlib *arg1 = (rlib *) 0 ;
    char *arg2 ;
    int result;
    
    arg1 = (rlib *)jarg1; 
    arg2 = jarg2; 
    result = (int)rlib_add_datasource_xml(arg1,arg2);
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_rlib_add_datasource_csv(void * jarg1, char * jarg2) {
    int jresult = 0 ;
    rlib *arg1 = (rlib *) 0 ;
    char *arg2 ;
    int result;
    
    arg1 = (rlib *)jarg1; 
    arg2 = jarg2; 
    result = (int)rlib_add_datasource_csv(arg1,arg2);
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_rlib_add_query_as(void * jarg1, char * jarg2, char * jarg3, char * jarg4) {
    int jresult = 0 ;
    rlib *arg1 = (rlib *) 0 ;
    char *arg2 ;
    char *arg3 ;
    char *arg4 ;
    int result;
    
    arg1 = (rlib *)jarg1; 
    arg2 = jarg2; 
    arg3 = jarg3; 
    arg4 = jarg4; 
    result = (int)rlib_add_query_as(arg1,arg2,arg3,arg4);
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_rlib_add_report(void * jarg1, char * jarg2) {
    int jresult = 0 ;
    rlib *arg1 = (rlib *) 0 ;
    char *arg2 ;
    int result;
    
    arg1 = (rlib *)jarg1; 
    arg2 = jarg2; 
    result = (int)rlib_add_report(arg1,arg2);
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_rlib_add_report_from_buffer(void * jarg1, char * jarg2) {
    int jresult = 0 ;
    rlib *arg1 = (rlib *) 0 ;
    char *arg2 ;
    int result;
    
    arg1 = (rlib *)jarg1; 
    arg2 = jarg2; 
    result = (int)rlib_add_report_from_buffer(arg1,arg2);
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_rlib_execute(void * jarg1) {
    int jresult = 0 ;
    rlib *arg1 = (rlib *) 0 ;
    int result;
    
    arg1 = (rlib *)jarg1; 
    result = (int)rlib_execute(arg1);
    
    jresult = result; 
    return jresult;
}


DllExport char * SWIGSTDCALL CSharp_rlib_get_content_type_as_text(void * jarg1) {
    char * jresult = 0 ;
    rlib *arg1 = (rlib *) 0 ;
    char *result;
    
    arg1 = (rlib *)jarg1; 
    result = (char *)rlib_get_content_type_as_text(arg1);
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_rlib_spool(void * jarg1) {
    int jresult = 0 ;
    rlib *arg1 = (rlib *) 0 ;
    int result;
    
    arg1 = (rlib *)jarg1; 
    result = (int)rlib_spool(arg1);
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_rlib_set_output_format(void * jarg1, int jarg2) {
    int jresult = 0 ;
    rlib *arg1 = (rlib *) 0 ;
    int arg2 ;
    int result;
    
    arg1 = (rlib *)jarg1; 
    arg2 = (int)jarg2; 
    result = (int)rlib_set_output_format(arg1,arg2);
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_rlib_add_resultset_follower_n_to_1(void * jarg1, char * jarg2, char * jarg3, char * jarg4, char * jarg5) {
    int jresult = 0 ;
    rlib *arg1 = (rlib *) 0 ;
    char *arg2 ;
    char *arg3 ;
    char *arg4 ;
    char *arg5 ;
    int result;
    
    arg1 = (rlib *)jarg1; 
    arg2 = jarg2; 
    arg3 = jarg3; 
    arg4 = jarg4; 
    arg5 = jarg5; 
    result = (int)rlib_add_resultset_follower_n_to_1(arg1,arg2,arg3,arg4,arg5);
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_rlib_add_resultset_follower(void * jarg1, char * jarg2, char * jarg3) {
    int jresult = 0 ;
    rlib *arg1 = (rlib *) 0 ;
    char *arg2 ;
    char *arg3 ;
    int result;
    
    arg1 = (rlib *)jarg1; 
    arg2 = jarg2; 
    arg3 = jarg3; 
    result = (int)rlib_add_resultset_follower(arg1,arg2,arg3);
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_rlib_set_output_format_from_text(void * jarg1, char * jarg2) {
    int jresult = 0 ;
    rlib *arg1 = (rlib *) 0 ;
    char *arg2 ;
    int result;
    
    arg1 = (rlib *)jarg1; 
    arg2 = jarg2; 
    result = (int)rlib_set_output_format_from_text(arg1,arg2);
    
    jresult = result; 
    return jresult;
}


DllExport char * SWIGSTDCALL CSharp_rlib_get_output(void * jarg1) {
    char * jresult = 0 ;
    rlib *arg1 = (rlib *) 0 ;
    char *result;
    
    arg1 = (rlib *)jarg1; 
    result = (char *)rlib_get_output(arg1);
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_rlib_get_output_length(void * jarg1) {
    int jresult = 0 ;
    rlib *arg1 = (rlib *) 0 ;
    int result;
    
    arg1 = (rlib *)jarg1; 
    result = (int)rlib_get_output_length(arg1);
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_rlib_signal_connect(void * jarg1, int jarg2, void * jarg3, void * jarg4) {
    int jresult = 0 ;
    rlib *arg1 = (rlib *) 0 ;
    int arg2 ;
    int (*arg3)(rlib *,void *) = (int (*)(rlib *,void *)) 0 ;
    void *arg4 = (void *) 0 ;
    int result;
    
    arg1 = (rlib *)jarg1; 
    arg2 = (int)jarg2; 
    arg3 = (int (*)(rlib *,void *))jarg3; 
    arg4 = (void *)jarg4; 
    result = (int)rlib_signal_connect(arg1,arg2,arg3,arg4);
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_rlib_signal_connect_string(void * jarg1, char * jarg2, void * jarg3, void * jarg4) {
    int jresult = 0 ;
    rlib *arg1 = (rlib *) 0 ;
    char *arg2 ;
    int (*arg3)(rlib *,void *) = (int (*)(rlib *,void *)) 0 ;
    void *arg4 = (void *) 0 ;
    int result;
    
    arg1 = (rlib *)jarg1; 
    arg2 = jarg2; 
    arg3 = (int (*)(rlib *,void *))jarg3; 
    arg4 = (void *)jarg4; 
    result = (int)rlib_signal_connect_string(arg1,arg2,arg3,arg4);
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_rlib_query_refresh(void * jarg1) {
    int jresult = 0 ;
    rlib *arg1 = (rlib *) 0 ;
    int result;
    
    arg1 = (rlib *)jarg1; 
    result = (int)rlib_query_refresh(arg1);
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_rlib_add_parameter(void * jarg1, char * jarg2, char * jarg3) {
    int jresult = 0 ;
    rlib *arg1 = (rlib *) 0 ;
    char *arg2 ;
    char *arg3 ;
    int result;
    
    arg1 = (rlib *)jarg1; 
    arg2 = jarg2; 
    arg3 = jarg3; 
    result = (int)rlib_add_parameter(arg1,(char const *)arg2,(char const *)arg3);
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_rlib_set_locale(void * jarg1, char * jarg2) {
    int jresult = 0 ;
    rlib *arg1 = (rlib *) 0 ;
    char *arg2 ;
    int result;
    
    arg1 = (rlib *)jarg1; 
    arg2 = jarg2; 
    result = (int)rlib_set_locale(arg1,arg2);
    
    jresult = result; 
    return jresult;
}


DllExport void SWIGSTDCALL CSharp_rlib_set_output_parameter(void * jarg1, char * jarg2, char * jarg3) {
    rlib *arg1 = (rlib *) 0 ;
    char *arg2 ;
    char *arg3 ;
    
    arg1 = (rlib *)jarg1; 
    arg2 = jarg2; 
    arg3 = jarg3; 
    rlib_set_output_parameter(arg1,arg2,arg3);
    
}


DllExport void SWIGSTDCALL CSharp_rlib_set_output_encoding(void * jarg1, char * jarg2) {
    rlib *arg1 = (rlib *) 0 ;
    char *arg2 ;
    
    arg1 = (rlib *)jarg1; 
    arg2 = jarg2; 
    rlib_set_output_encoding(arg1,(char const *)arg2);
    
}


DllExport int SWIGSTDCALL CSharp_rlib_set_datasource_encoding(void * jarg1, char * jarg2, char * jarg3) {
    int jresult = 0 ;
    rlib *arg1 = (rlib *) 0 ;
    char *arg2 ;
    char *arg3 ;
    int result;
    
    arg1 = (rlib *)jarg1; 
    arg2 = jarg2; 
    arg3 = jarg3; 
    result = (int)rlib_set_datasource_encoding(arg1,arg2,arg3);
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_rlib_free(void * jarg1) {
    int jresult = 0 ;
    rlib *arg1 = (rlib *) 0 ;
    int result;
    
    arg1 = (rlib *)jarg1; 
    result = (int)rlib_free(arg1);
    
    jresult = result; 
    return jresult;
}


DllExport char * SWIGSTDCALL CSharp_rlib_version() {
    char * jresult = 0 ;
    char *result;
    
    result = (char *)rlib_version();
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_rlib_graph_add_bg_region(void * jarg1, char * jarg2, char * jarg3, char * jarg4, float jarg5, float jarg6) {
    int jresult = 0 ;
    rlib *arg1 = (rlib *) 0 ;
    char *arg2 ;
    char *arg3 ;
    char *arg4 ;
    float arg5 ;
    float arg6 ;
    int result;
    
    arg1 = (rlib *)jarg1; 
    arg2 = jarg2; 
    arg3 = jarg3; 
    arg4 = jarg4; 
    arg5 = (float)jarg5; 
    arg6 = (float)jarg6; 
    result = (int)rlib_graph_add_bg_region(arg1,arg2,arg3,arg4,arg5,arg6);
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_rlib_graph_clear_bg_region(void * jarg1, char * jarg2) {
    int jresult = 0 ;
    rlib *arg1 = (rlib *) 0 ;
    char *arg2 ;
    int result;
    
    arg1 = (rlib *)jarg1; 
    arg2 = jarg2; 
    result = (int)rlib_graph_clear_bg_region(arg1,arg2);
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_rlib_graph_set_x_minor_tick(void * jarg1, char * jarg2, char * jarg3) {
    int jresult = 0 ;
    rlib *arg1 = (rlib *) 0 ;
    char *arg2 ;
    char *arg3 ;
    int result;
    
    arg1 = (rlib *)jarg1; 
    arg2 = jarg2; 
    arg3 = jarg3; 
    result = (int)rlib_graph_set_x_minor_tick(arg1,arg2,arg3);
    
    jresult = result; 
    return jresult;
}


DllExport int SWIGSTDCALL CSharp_rlib_graph_set_x_minor_tick_by_location(void * jarg1, char * jarg2, int jarg3) {
    int jresult = 0 ;
    rlib *arg1 = (rlib *) 0 ;
    char *arg2 ;
    int arg3 ;
    int result;
    
    arg1 = (rlib *)jarg1; 
    arg2 = jarg2; 
    arg3 = (int)jarg3; 
    result = (int)rlib_graph_set_x_minor_tick_by_location(arg1,arg2,arg3);
    
    jresult = result; 
    return jresult;
}


#ifdef __cplusplus
}
#endif

