/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.21
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


class librlibJNI {
  public final static native long rlib_init();
  public final static native int rlib_add_datasource_mysql(long jarg1, String jarg2, String jarg3, String jarg4, String jarg5, String jarg6);
  public final static native int rlib_add_datasource_postgre(long jarg1, String jarg2, String jarg3);
  public final static native int rlib_add_query_as(long jarg1, String jarg2, String jarg3, String jarg4);
  public final static native int rlib_add_report(long jarg1, String jarg2, String jarg3);
  public final static native int rlib_execute(long jarg1);
  public final static native int rlib_set_output_format_from_text(long jarg1, String jarg2);
  public final static native int rlib_spool(long jarg1);
  public final static native int rlib_free(long jarg1);
  public final static native String rlib_get_output(long jarg1);
  public final static native int rlib_get_output_length(long jarg1);
  public final static native int rlib_mysql_report(String jarg1, String jarg2, String jarg3, String jarg4, String jarg5, String jarg6, String jarg7);
  public final static native int rlib_postgre_report(String jarg1, String jarg2, String jarg3, String jarg4);
  public final static native int rlib_add_datasource_odbc(long jarg1, String jarg2, String jarg3, String jarg4, String jarg5);
  public final static native int rlib_add_resultset_follower(long jarg1, String jarg2, String jarg3);
  public final static native int rlib_add_parameter(long jarg1, String jarg2, String jarg3);
  public final static native String rlib_version();
  public final static native void rlib_set_output_encoding(long jarg1, String jarg2);
  public final static native void rlib_set_report_output_encoding(long jarg1, int jarg2, String jarg3);
  public final static native void rlib_set_pdf_font(long jarg1, String jarg2, String jarg3);
  public final static native void rlib_set_pdf_font_directories(long jarg1, String jarg2, String jarg3);
}
