# This file was automatically generated by SWIG
package librlib;
require Exporter;
require DynaLoader;
@ISA = qw(Exporter DynaLoader);
package librlibc;
bootstrap librlib;
package librlib;
@EXPORT = qw( );

# ---------- BASE METHODS -------------

package librlib;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package librlib;

*rlib_init = *librlibc::rlib_init;
*rlib_add_datasource_mysql = *librlibc::rlib_add_datasource_mysql;
*rlib_add_datasource_postgre = *librlibc::rlib_add_datasource_postgre;
*rlib_add_query_as = *librlibc::rlib_add_query_as;
*rlib_add_report = *librlibc::rlib_add_report;
*rlib_execute = *librlibc::rlib_execute;
*rlib_set_output_format_from_text = *librlibc::rlib_set_output_format_from_text;
*rlib_spool = *librlibc::rlib_spool;
*rlib_free = *librlibc::rlib_free;
*rlib_get_output = *librlibc::rlib_get_output;
*rlib_get_output_length = *librlibc::rlib_get_output_length;
*rlib_mysql_report = *librlibc::rlib_mysql_report;
*rlib_postgre_report = *librlibc::rlib_postgre_report;
*rlib_add_datasource_odbc = *librlibc::rlib_add_datasource_odbc;
*rlib_add_resultset_follower = *librlibc::rlib_add_resultset_follower;
*rlib_add_parameter = *librlibc::rlib_add_parameter;
*rlib_version = *librlibc::rlib_version;
*rlib_set_output_encoding = *librlibc::rlib_set_output_encoding;
*rlib_set_report_output_encoding = *librlibc::rlib_set_report_output_encoding;
*rlib_set_pdf_font = *librlibc::rlib_set_pdf_font;
*rlib_set_pdf_font_directories = *librlibc::rlib_set_pdf_font_directories;

# ------- VARIABLE STUBS --------

package librlib;

1;
