# This file was automatically generated by SWIG
package librlib;
require Exporter;
require DynaLoader;
@ISA = qw(Exporter DynaLoader);
package librlibc;
bootstrap librlib;
package librlib;
@EXPORT = qw( );

# ---------- BASE METHODS -------------

package librlib;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package librlib;

*rlib_init = *librlibc::rlib_init;
*rlib_add_datasource_mysql = *librlibc::rlib_add_datasource_mysql;
*rlib_add_datasource_postgre = *librlibc::rlib_add_datasource_postgre;
*rlib_add_datasource_odbc = *librlibc::rlib_add_datasource_odbc;
*rlib_add_query_as = *librlibc::rlib_add_query_as;
*rlib_add_report = *librlibc::rlib_add_report;
*rlib_add_report_from_buffer = *librlibc::rlib_add_report_from_buffer;
*rlib_execute = *librlibc::rlib_execute;
*rlib_get_content_type_as_text = *librlibc::rlib_get_content_type_as_text;
*rlib_spool = *librlibc::rlib_spool;
*rlib_set_output_format = *librlibc::rlib_set_output_format;
*rlib_add_resultset_follower_n_to_1 = *librlibc::rlib_add_resultset_follower_n_to_1;
*rlib_add_resultset_follower = *librlibc::rlib_add_resultset_follower;
*rlib_set_output_format_from_text = *librlibc::rlib_set_output_format_from_text;
*rlib_get_output = *librlibc::rlib_get_output;
*rlib_get_output_length = *librlibc::rlib_get_output_length;
*rlib_signal_connect = *librlibc::rlib_signal_connect;
*rlib_signal_connect_string = *librlibc::rlib_signal_connect_string;
*rlib_query_refresh = *librlibc::rlib_query_refresh;
*rlib_add_parameter = *librlibc::rlib_add_parameter;
*rlib_set_locale = *librlibc::rlib_set_locale;
*rlib_set_output_parameter = *librlibc::rlib_set_output_parameter;
*rlib_set_output_encoding = *librlibc::rlib_set_output_encoding;
*rlib_set_database_encoding = *librlibc::rlib_set_database_encoding;
*rlib_set_datasource_encoding = *librlibc::rlib_set_datasource_encoding;
*rlib_set_parameter_encoding = *librlibc::rlib_set_parameter_encoding;
*rlib_set_encodings = *librlibc::rlib_set_encodings;
*rlib_free = *librlibc::rlib_free;
*rlib_version = *librlibc::rlib_version;

# ------- VARIABLE STUBS --------

package librlib;

1;
