/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.21
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class librlib {
  public static SWIGTYPE_p_rlib rlib_init() {
    long cPtr = librlibJNI.rlib_init();
    return (cPtr == 0) ? null : new SWIGTYPE_p_rlib(cPtr, false);
  }

  public static int rlib_add_datasource_mysql(SWIGTYPE_p_rlib r, String input_name, String database_host, String database_user, String database_password, String database_database) {
    return librlibJNI.rlib_add_datasource_mysql(SWIGTYPE_p_rlib.getCPtr(r), input_name, database_host, database_user, database_password, database_database);
  }

  public static int rlib_add_datasource_postgre(SWIGTYPE_p_rlib r, String input_name, String conn) {
    return librlibJNI.rlib_add_datasource_postgre(SWIGTYPE_p_rlib.getCPtr(r), input_name, conn);
  }

  public static int rlib_add_query_as(SWIGTYPE_p_rlib r, String input_source, String sql, String name) {
    return librlibJNI.rlib_add_query_as(SWIGTYPE_p_rlib.getCPtr(r), input_source, sql, name);
  }

  public static int rlib_add_report(SWIGTYPE_p_rlib r, String name, String mainloop) {
    return librlibJNI.rlib_add_report(SWIGTYPE_p_rlib.getCPtr(r), name, mainloop);
  }

  public static int rlib_execute(SWIGTYPE_p_rlib r) {
    return librlibJNI.rlib_execute(SWIGTYPE_p_rlib.getCPtr(r));
  }

  public static int rlib_set_output_format_from_text(SWIGTYPE_p_rlib r, String name) {
    return librlibJNI.rlib_set_output_format_from_text(SWIGTYPE_p_rlib.getCPtr(r), name);
  }

  public static int rlib_spool(SWIGTYPE_p_rlib r) {
    return librlibJNI.rlib_spool(SWIGTYPE_p_rlib.getCPtr(r));
  }

  public static int rlib_free(SWIGTYPE_p_rlib r) {
    return librlibJNI.rlib_free(SWIGTYPE_p_rlib.getCPtr(r));
  }

  public static String rlib_get_output(SWIGTYPE_p_rlib r) {
    return librlibJNI.rlib_get_output(SWIGTYPE_p_rlib.getCPtr(r));
  }

  public static int rlib_get_output_length(SWIGTYPE_p_rlib r) {
    return librlibJNI.rlib_get_output_length(SWIGTYPE_p_rlib.getCPtr(r));
  }

  public static int rlib_mysql_report(String hostname, String username, String password, String database, String xmlfilename, String sqlquery, String outputformat) {
    return librlibJNI.rlib_mysql_report(hostname, username, password, database, xmlfilename, sqlquery, outputformat);
  }

  public static int rlib_postgre_report(String connstr, String xmlfilename, String sqlquery, String outputformat) {
    return librlibJNI.rlib_postgre_report(connstr, xmlfilename, sqlquery, outputformat);
  }

  public static int rlib_add_datasource_odbc(SWIGTYPE_p_rlib r, String input_name, String source, String user, String password) {
    return librlibJNI.rlib_add_datasource_odbc(SWIGTYPE_p_rlib.getCPtr(r), input_name, source, user, password);
  }

  public static int rlib_add_resultset_follower(SWIGTYPE_p_rlib r, String leader, String follower) {
    return librlibJNI.rlib_add_resultset_follower(SWIGTYPE_p_rlib.getCPtr(r), leader, follower);
  }

  public static int rlib_add_parameter(SWIGTYPE_p_rlib r, String name, String value) {
    return librlibJNI.rlib_add_parameter(SWIGTYPE_p_rlib.getCPtr(r), name, value);
  }

  public static String rlib_version() {
    return librlibJNI.rlib_version();
  }

  public static void rlib_set_output_encoding(SWIGTYPE_p_rlib r, String encoding) {
    librlibJNI.rlib_set_output_encoding(SWIGTYPE_p_rlib.getCPtr(r), encoding);
  }

  public static void rlib_set_report_output_encoding(SWIGTYPE_p_rlib r, int reportnum, String encoding) {
    librlibJNI.rlib_set_report_output_encoding(SWIGTYPE_p_rlib.getCPtr(r), reportnum, encoding);
  }

  public static void rlib_set_pdf_font(SWIGTYPE_p_rlib r, String encoding, String fontname) {
    librlibJNI.rlib_set_pdf_font(SWIGTYPE_p_rlib.getCPtr(r), encoding, fontname);
  }

  public static void rlib_set_pdf_font_directories(SWIGTYPE_p_rlib r, String d1, String d2) {
    librlibJNI.rlib_set_pdf_font_directories(SWIGTYPE_p_rlib.getCPtr(r), d1, d2);
  }

}
