/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.21
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;

public class rlib {
  public static SWIGTYPE_p_rlib rlib_init() {
    IntPtr cPtr = rlibPINVOKE.rlib_init();
    return (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_rlib(cPtr, false);
  }

  public static int rlib_add_datasource_mysql(SWIGTYPE_p_rlib r, string input_name, string database_host, string database_user, string database_password, string database_database) {
    return rlibPINVOKE.rlib_add_datasource_mysql(SWIGTYPE_p_rlib.getCPtr(r), input_name, database_host, database_user, database_password, database_database);
  }

  public static int rlib_add_datasource_postgres(SWIGTYPE_p_rlib r, string input_name, string conn) {
    return rlibPINVOKE.rlib_add_datasource_postgres(SWIGTYPE_p_rlib.getCPtr(r), input_name, conn);
  }

  public static int rlib_add_datasource_odbc(SWIGTYPE_p_rlib r, string input_name, string source, string user, string password) {
    return rlibPINVOKE.rlib_add_datasource_odbc(SWIGTYPE_p_rlib.getCPtr(r), input_name, source, user, password);
  }

  public static int rlib_add_datasource_xml(SWIGTYPE_p_rlib r, string input_name) {
    return rlibPINVOKE.rlib_add_datasource_xml(SWIGTYPE_p_rlib.getCPtr(r), input_name);
  }

  public static int rlib_add_datasource_csv(SWIGTYPE_p_rlib r, string input_name) {
    return rlibPINVOKE.rlib_add_datasource_csv(SWIGTYPE_p_rlib.getCPtr(r), input_name);
  }

  public static int rlib_add_query_as(SWIGTYPE_p_rlib r, string input_source, string sql, string name) {
    return rlibPINVOKE.rlib_add_query_as(SWIGTYPE_p_rlib.getCPtr(r), input_source, sql, name);
  }

  public static int rlib_add_report(SWIGTYPE_p_rlib r, string name) {
    return rlibPINVOKE.rlib_add_report(SWIGTYPE_p_rlib.getCPtr(r), name);
  }

  public static int rlib_add_report_from_buffer(SWIGTYPE_p_rlib r, string buffer) {
    return rlibPINVOKE.rlib_add_report_from_buffer(SWIGTYPE_p_rlib.getCPtr(r), buffer);
  }

  public static int rlib_execute(SWIGTYPE_p_rlib r) {
    return rlibPINVOKE.rlib_execute(SWIGTYPE_p_rlib.getCPtr(r));
  }

  public static string rlib_get_content_type_as_text(SWIGTYPE_p_rlib r) {
    return rlibPINVOKE.rlib_get_content_type_as_text(SWIGTYPE_p_rlib.getCPtr(r));
  }

  public static int rlib_spool(SWIGTYPE_p_rlib r) {
    return rlibPINVOKE.rlib_spool(SWIGTYPE_p_rlib.getCPtr(r));
  }

  public static int rlib_set_output_format(SWIGTYPE_p_rlib r, int format) {
    return rlibPINVOKE.rlib_set_output_format(SWIGTYPE_p_rlib.getCPtr(r), format);
  }

  public static int rlib_add_resultset_follower_n_to_1(SWIGTYPE_p_rlib r, string leader, string leader_field, string follower, string follower_field) {
    return rlibPINVOKE.rlib_add_resultset_follower_n_to_1(SWIGTYPE_p_rlib.getCPtr(r), leader, leader_field, follower, follower_field);
  }

  public static int rlib_add_resultset_follower(SWIGTYPE_p_rlib r, string leader, string follower) {
    return rlibPINVOKE.rlib_add_resultset_follower(SWIGTYPE_p_rlib.getCPtr(r), leader, follower);
  }

  public static int rlib_set_output_format_from_text(SWIGTYPE_p_rlib r, string name) {
    return rlibPINVOKE.rlib_set_output_format_from_text(SWIGTYPE_p_rlib.getCPtr(r), name);
  }

  public static string rlib_get_output(SWIGTYPE_p_rlib r) {
    return rlibPINVOKE.rlib_get_output(SWIGTYPE_p_rlib.getCPtr(r));
  }

  public static int rlib_get_output_length(SWIGTYPE_p_rlib r) {
    return rlibPINVOKE.rlib_get_output_length(SWIGTYPE_p_rlib.getCPtr(r));
  }

  public static int rlib_signal_connect(SWIGTYPE_p_rlib r, int signal_number, SWIGTYPE_p_f_p_rlib_p_void__int signal_function, SWIGTYPE_p_void data) {
    return rlibPINVOKE.rlib_signal_connect(SWIGTYPE_p_rlib.getCPtr(r), signal_number, SWIGTYPE_p_f_p_rlib_p_void__int.getCPtr(signal_function), SWIGTYPE_p_void.getCPtr(data));
  }

  public static int rlib_signal_connect_string(SWIGTYPE_p_rlib r, string signal_name, SWIGTYPE_p_f_p_rlib_p_void__int signal_function, SWIGTYPE_p_void data) {
    return rlibPINVOKE.rlib_signal_connect_string(SWIGTYPE_p_rlib.getCPtr(r), signal_name, SWIGTYPE_p_f_p_rlib_p_void__int.getCPtr(signal_function), SWIGTYPE_p_void.getCPtr(data));
  }

  public static int rlib_query_refresh(SWIGTYPE_p_rlib r) {
    return rlibPINVOKE.rlib_query_refresh(SWIGTYPE_p_rlib.getCPtr(r));
  }

  public static int rlib_add_parameter(SWIGTYPE_p_rlib r, string name, string value) {
    return rlibPINVOKE.rlib_add_parameter(SWIGTYPE_p_rlib.getCPtr(r), name, value);
  }

  public static int rlib_set_locale(SWIGTYPE_p_rlib r, string locale) {
    return rlibPINVOKE.rlib_set_locale(SWIGTYPE_p_rlib.getCPtr(r), locale);
  }

  public static void rlib_set_output_parameter(SWIGTYPE_p_rlib r, string parameter, string value) {
    rlibPINVOKE.rlib_set_output_parameter(SWIGTYPE_p_rlib.getCPtr(r), parameter, value);
  }

  public static void rlib_set_output_encoding(SWIGTYPE_p_rlib r, string encoding) {
    rlibPINVOKE.rlib_set_output_encoding(SWIGTYPE_p_rlib.getCPtr(r), encoding);
  }

  public static int rlib_set_datasource_encoding(SWIGTYPE_p_rlib r, string input_name, string encoding) {
    return rlibPINVOKE.rlib_set_datasource_encoding(SWIGTYPE_p_rlib.getCPtr(r), input_name, encoding);
  }

  public static int rlib_free(SWIGTYPE_p_rlib r) {
    return rlibPINVOKE.rlib_free(SWIGTYPE_p_rlib.getCPtr(r));
  }

  public static string rlib_version() {
    return rlibPINVOKE.rlib_version();
  }

  public static int rlib_graph_add_bg_region(SWIGTYPE_p_rlib r, string graph_name, string region_label, string color, float start, float end) {
    return rlibPINVOKE.rlib_graph_add_bg_region(SWIGTYPE_p_rlib.getCPtr(r), graph_name, region_label, color, start, end);
  }

  public static int rlib_graph_clear_bg_region(SWIGTYPE_p_rlib r, string graph_name) {
    return rlibPINVOKE.rlib_graph_clear_bg_region(SWIGTYPE_p_rlib.getCPtr(r), graph_name);
  }

  public static int rlib_graph_set_x_minor_tick(SWIGTYPE_p_rlib r, string graph_name, string x_value) {
    return rlibPINVOKE.rlib_graph_set_x_minor_tick(SWIGTYPE_p_rlib.getCPtr(r), graph_name, x_value);
  }

  public static int rlib_graph_set_x_minor_tick_by_location(SWIGTYPE_p_rlib r, string graph_name, int location) {
    return rlibPINVOKE.rlib_graph_set_x_minor_tick_by_location(SWIGTYPE_p_rlib.getCPtr(r), graph_name, location);
  }

}
