# This file was automatically generated by SWIG
package rlib;
require Exporter;
require DynaLoader;
@ISA = qw(Exporter DynaLoader);
package rlibc;
bootstrap rlib;
package rlib;
@EXPORT = qw( );

# ---------- BASE METHODS -------------

package rlib;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package rlib;

*rlib_init = *rlibc::rlib_init;
*rlib_add_datasource_mysql = *rlibc::rlib_add_datasource_mysql;
*rlib_add_datasource_postgres = *rlibc::rlib_add_datasource_postgres;
*rlib_add_datasource_odbc = *rlibc::rlib_add_datasource_odbc;
*rlib_add_datasource_xml = *rlibc::rlib_add_datasource_xml;
*rlib_add_datasource_csv = *rlibc::rlib_add_datasource_csv;
*rlib_add_query_as = *rlibc::rlib_add_query_as;
*rlib_add_report = *rlibc::rlib_add_report;
*rlib_add_report_from_buffer = *rlibc::rlib_add_report_from_buffer;
*rlib_execute = *rlibc::rlib_execute;
*rlib_get_content_type_as_text = *rlibc::rlib_get_content_type_as_text;
*rlib_spool = *rlibc::rlib_spool;
*rlib_set_output_format = *rlibc::rlib_set_output_format;
*rlib_add_resultset_follower_n_to_1 = *rlibc::rlib_add_resultset_follower_n_to_1;
*rlib_add_resultset_follower = *rlibc::rlib_add_resultset_follower;
*rlib_set_output_format_from_text = *rlibc::rlib_set_output_format_from_text;
*rlib_get_output = *rlibc::rlib_get_output;
*rlib_get_output_length = *rlibc::rlib_get_output_length;
*rlib_signal_connect = *rlibc::rlib_signal_connect;
*rlib_signal_connect_string = *rlibc::rlib_signal_connect_string;
*rlib_query_refresh = *rlibc::rlib_query_refresh;
*rlib_add_parameter = *rlibc::rlib_add_parameter;
*rlib_set_locale = *rlibc::rlib_set_locale;
*rlib_set_output_parameter = *rlibc::rlib_set_output_parameter;
*rlib_set_output_encoding = *rlibc::rlib_set_output_encoding;
*rlib_set_datasource_encoding = *rlibc::rlib_set_datasource_encoding;
*rlib_free = *rlibc::rlib_free;
*rlib_version = *rlibc::rlib_version;
*rlib_graph_add_bg_region = *rlibc::rlib_graph_add_bg_region;
*rlib_graph_clear_bg_region = *rlibc::rlib_graph_clear_bg_region;
*rlib_graph_set_x_minor_tick = *rlibc::rlib_graph_set_x_minor_tick;
*rlib_graph_set_x_minor_tick_by_location = *rlibc::rlib_graph_set_x_minor_tick_by_location;

# ------- VARIABLE STUBS --------

package rlib;

1;
