/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.21
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

using System;
public class SWIGTYPE_p_rlib {
  private IntPtr swigCPtr;

  internal SWIGTYPE_p_rlib(IntPtr cPtr, bool bFutureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_rlib() {
    swigCPtr = IntPtr.Zero;
  }

  internal static IntPtr getCPtr(SWIGTYPE_p_rlib obj) {
    return (obj == null) ? IntPtr.Zero : obj.swigCPtr;
  }
}

